# Generated by Django 3.1.5 on 2021-01-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mixipyapp.page')),
            ],
        ),
        migrations.CreateModel(
            name='Spotify_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_url', models.CharField(max_length=50)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mixipyapp.search')),
            ],
        ),
        migrations.CreateModel(
            name='Request_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mixipyapp.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mixipyapp.platform')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mixipyapp.request_log')),
            ],
        ),
        migrations.CreateModel(
            name='Page_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mixipyapp.page')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mixipyapp.request_log')),
            ],
        ),
    ]
