# Generated by Django 3.1.5 on 2021-01-08 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_log',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
