# Generated by Django 3.1.5 on 2021-01-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0003_playlist_uri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotify_track',
            old_name='spotify_url',
            new_name='spotify_uri',
        ),
        migrations.AlterField(
            model_name='platform',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='request_log',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
