# Generated by Django 3.1.5 on 2021-01-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0004_auto_20210108_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
