# Generated by Django 3.1.5 on 2021-01-08 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0006_auto_20210108_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='request_log',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='mixipyapp.request_log'),
            preserve_default=False,
        ),
    ]
