# Generated by Django 3.1.5 on 2021-01-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0008_auto_20210108_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
