# Generated by Django 3.1.5 on 2021-01-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0010_request_log_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotify_track',
            old_name='spotify_uri',
            new_name='uri',
        ),
    ]
