# Generated by Django 3.1.5 on 2021-01-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0011_auto_20210109_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request_log',
            new_name='RequestLog',
        ),
    ]
