# Generated by Django 3.1.5 on 2021-01-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0012_auto_20210110_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestLog',
            new_name='Request_Log',
        ),
    ]
