# Generated by Django 3.1.5 on 2021-01-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0013_auto_20210110_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request_Log',
            new_name='RequestLog',
        ),
    ]
