# Generated by Django 3.1.5 on 2021-01-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0014_auto_20210110_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spotify_track',
            new_name='Track',
        ),
    ]
