# Generated by Django 3.1.5 on 2021-01-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0015_auto_20210110_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page_requests',
            new_name='PageRequest',
        ),
        migrations.AlterField(
            model_name='page',
            name='request_log',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mixipyapp.requestlog'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
