# Generated by Django 3.1.5 on 2021-01-10 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0017_auto_20210110_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 13, 14, 9, 895743, tzinfo=utc)),
        ),
    ]
