# Generated by Django 3.1.5 on 2021-01-10 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0018_auto_20210110_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
