# Generated by Django 3.1.5 on 2021-01-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0019_auto_20210110_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
