# Generated by Django 3.1.5 on 2021-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0020_auto_20210110_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
