# Generated by Django 3.1.5 on 2021-01-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0021_auto_20210110_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='status',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
