# Generated by Django 3.1.5 on 2021-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0022_requestlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='modified_datetime',
            field=models.DateTimeField(),
        ),
    ]
