# Generated by Django 3.1.5 on 2021-01-11 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0024_auto_20210110_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='modified_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
