# Generated by Django 3.1.5 on 2021-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0025_auto_20210111_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='uri',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
