# Generated by Django 3.1.5 on 2021-01-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0026_auto_20210114_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
