# Generated by Django 3.1.5 on 2021-01-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0027_page_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchString',
            fields=[
                ('keywords', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
