# Generated by Django 3.1.5 on 2021-01-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0028_searchstring'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchString',
            new_name='SearchKey',
        ),
    ]
