# Generated by Django 3.1.5 on 2021-01-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0029_auto_20210118_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchKey',
            new_name='SearchQuery',
        ),
    ]
