# Generated by Django 3.1.5 on 2021-01-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixipyapp', '0031_auto_20210118_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='key',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
